stages:
  - build
  - updateManifest

variables:
  DOCKER_DRIVER: overlay2
  RUNNER_ID: ${CI_JOB_ID}
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}
  REPO_MANIFEST_NAME: aura-network
  REPO_MANIFEST_URL: git@gitlab.com:akachain/gitops/aura-network.git
  REPO_MANIFEST_BRANCH: master
  REPO_MANIFEST_ENV_DEV: ./clusters/k8s-dev
  REPO_MANIFEST_ENV_QA: ./clusters/k8s-qa
  REPO_MANIFEST_ENV_UAT: ./clusters/k8s-uat
  REPO_MANIFEST_TAG_IMAGE: image_landing_page

build:
  stage: build
  tags:
    - build
    - akcCluster
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /data/app/node_modules
  script:
    - chmod 777 -R ./ci
    - ./ci/build.sh
  only:
    - develop
    - uat
    - qa

updateManifest:
  stage: updateManifest
  tags:
    - build
    - akcCluster
  script:
    - chmod 777 -R ./ci
    - ./ci/updateManifest.sh
  only:
    - develop
    - uat
    - qa
