name: Continuous integration

on:
  push:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: "dist/frontend"
          bucket: ${{ secrets.AWS_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          #dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          #invalidation: /
          delete-removed: true
          no-cache: true
          private: true

      
  
